# Generated by Django 4.2.7 on 2023-12-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='surname',
        ),
    ]
