# Generated by Django 4.2.7 on 2023-12-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_name_booking_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nickname', models.CharField(max_length=25, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2023-12-24', verbose_name='date'),
        ),
    ]
