# Generated by Django 4.2.7 on 2023-12-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_register_alter_booking_options_alter_booking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
